import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case russian = "ru"

    var id: String { rawValue }

    var title: String {
        switch self {
        case .english: "English"
        case .russian: "Русский"
        }
    }
}

enum L10n {
    private static let languageKey = "applicationLanguage"
    private static var overrideLanguage: AppLanguage?

    static var language: AppLanguage {
        overrideLanguage
            ?? UserDefaults.standard.string(forKey: languageKey).flatMap(AppLanguage.init(rawValue:))
            ?? .english
    }

    static func configure(_ language: AppLanguage) {
        overrideLanguage = language
        UserDefaults.standard.set(language.rawValue, forKey: languageKey)
    }

    static func text(_ russian: String) -> String {
        guard language == .english else { return russian }
        if let exact = english[russian] { return exact }

        var translated = russian
        for (source, replacement) in fragments where translated.contains(source) {
            translated = translated.replacingOccurrences(of: source, with: replacement)
        }
        return translated
    }

    static func choose(english: String, russian: String) -> String {
        language == .english ? english : russian
    }

    private static let english: [String: String] = [
        "Без сжатия": "No compression",
        "Без изменений": "No changes",
        "Уменьшить образ": "Shrink image",
        "Нет": "None",
        "Считать образ": "Create image",
        "Записать образ": "Flash image",
        "Из файла": "From file",
        "По URL": "From URL",
        "Клонировать": "Clone drive",
        "Подготовка": "Preparing",
        "Загрузка образа": "Downloading image",
        "Анализ разделов": "Analyzing partitions",
        "Копирование носителя": "Copying drive",
        "Уменьшение образа": "Shrinking image",
        "Архивация образа": "Compressing image",
        "Проверка образа": "Verifying image",
        "Запись образа": "Flashing image",
        "Проверка записи": "Verifying write",
        "Завершение": "Finalizing",
        "Готово": "Completed",
        "Отменено": "Cancelled",
        "Ошибка": "Error",
        "Настройки": "Settings",
        "FAQ": "FAQ",
        "Параметры следующего образа": "Next image options",
        "Язык": "Language",
        "Обработка образа": "Image processing",
        "Расширять ext при первой загрузке": "Expand ext on first boot",
        "Автоматически извлекать носитель": "Automatically eject drive",
        "После считывания образа": "After creating an image",
        "После записи образа": "After flashing an image",
        "Проверка готовности": "Readiness check",
        "Лицензии": "Licenses",
        "Поддерживаемые носители": "Supported drives",
        "Внешние SD-карты, USB-флешки, SSD и жесткие диски, которые macOS видит как физический диск.": "External SD cards, USB flash drives, SSDs, and hard drives that macOS exposes as physical disks.",
        "Что делает уменьшение": "How shrinking works",
        "Уменьшает последний основной раздел ext2/3/4 в MBR, обрабатывает свободные блоки и может расширить rootfs при первой загрузке. Использует встроенные e2fsprogs и не требует Docker.": "Shrinks the last primary ext2/3/4 partition in an MBR image, processes free blocks, and can expand rootfs on first boot. Uses bundled e2fsprogs and does not require Docker.",
        "Проверка после записи": "Post-write verification",
        "Запускается автоматически. Когда проверка начнется, ее можно пропустить отдельной кнопкой; автоматическое извлечение выполняется только после проверки или ее пропуска.": "Starts automatically. Once verification begins, it can be skipped with a separate button. Automatic ejection happens only after verification finishes or is skipped.",
        "Права macOS": "macOS permissions",
        "Для прямого доступа приложение запросит пароль администратора. При ошибке Operation not permitted включите «Полный доступ к диску» и перезапустите приложение.": "The app requests an administrator password for direct disk access. If Operation not permitted appears, enable Full Disk Access and restart the app.",
        "Выберите носитель": "Select a drive",
        "Источник образа": "Image source",
        "Выберите целевой носитель": "Select the target drive",
        "Параметры образа": "Image options",
        "Расположение": "Location",
        "Название": "Name",
        "Выбрать папку": "Select folder",
        "Ищем внешние накопители…": "Looking for external drives…",
        "Носитель не найден": "No drive found",
        "Носители не найдены": "No drives found",
        "Подключите второй носитель": "Connect a second drive",
        "СЖАТИЕ": "COMPRESSION",
        "Выбрать источник образа": "Select image source",
        "Ссылка на файл образа": "Direct image file URL",
        "Открыть файл образа": "Open image file",
        "Выбрать": "Select",
        "Изменить": "Change",
        "Исходный носитель": "Source drive",
        "Целевой носитель": "Target drive",
        "Пропустить проверку": "Skip verification",
        "Остановить операцию": "Stop operation",
        "Начать считывание": "Create image",
        "Начать запись": "Flash image",
        "Скачать и записать": "Download and flash",
        "Начать клонирование": "Start cloning",
        "Открыть настройки": "Open Settings",
        "Обновить список носителей": "Refresh drive list",
        "Обновить список устройств": "Refresh drive list",
        "Коротко о работе": "Quick guide",
        "Какие носители поддерживаются?": "Which drives are supported?",
        "Что делает уменьшение ext?": "What does ext shrinking do?",
        "Какие образы поддерживаются?": "Which image formats are supported?",
        "IMG, RAW и DD без сжатия или в ZSTD, GZIP, XZ, BZIP2, LZ4, ZIP и 7Z. Отдельный JSON не создается.": "IMG, RAW, and DD, uncompressed or compressed with ZSTD, GZIP, XZ, BZIP2, LZ4, ZIP, or 7Z. No sidecar JSON is created.",
        "Можно ли записать на меньший диск?": "Can I flash to a smaller drive?",
        "Да, если образ был уменьшен. Целевой носитель должен вмещать итоговый логический размер файла.": "Yes, if the image was shrunk. The target drive must fit the final logical image size.",
        "Simple Imager готовится к работе": "Preparing Simple Imager",
        "Проверим совместимость, встроенные инструменты и подпись приложения.": "Checking compatibility, bundled tools, and the application signature.",
        "Настройки доступа": "Access Settings",
        "Проверить снова": "Check Again",
        "Продолжить": "Continue",
        "Apple Silicon": "Apple Silicon",
        "Встроенные компоненты": "Bundled Components",
        "Компоненты macOS": "macOS Components",
        "Подпись приложения": "Application Signature",
        "Доступ к накопителям": "Drive Access",
        "Архитектура arm64 поддерживается.": "The arm64 architecture is supported.",
        "Эта версия предназначена только для Mac с процессором серии M.": "This version supports only Apple silicon Macs.",
        "macOS запросит пароль администратора. Если прямой доступ будет заблокирован, включите для приложения «Полный доступ к диску».": "macOS will request an administrator password. If direct access is blocked, enable Full Disk Access for the application.",
        "Манифест автономного runtime отсутствует или повреждён. Переустановите приложение.": "The bundled runtime manifest is missing or damaged. Reinstall the application.",
        "Все необходимые системные компоненты доступны.": "All required system components are available.",
        "Проверка доступна в собранном .app.": "Signature verification is available in the built .app.",
        "Подпись и вложенные исполняемые файлы действительны.": "The application and bundled executables have valid signatures.",
        "Подпись повреждена. Переустановите приложение из доверенного источника.": "The signature is damaged. Reinstall the application from a trusted source.",
        "Каждый сектор сохраняется без изменений, включая содержимое свободного места.": "Every sector is preserved unchanged, including the contents of free space.",
        "Последний основной раздел ext2/3/4 и логический размер MBR-образа уменьшаются, а свободные блоки зануляются.": "The last primary ext2/3/4 partition and the logical MBR image size are reduced, and free blocks are zeroed.",
        "Операция отменена.": "Operation cancelled.",
        "Операция отменена. Носитель может содержать незавершенные данные.": "Operation cancelled. The drive may contain incomplete data.",
        "Карта записана и полностью проверена.": "The drive was flashed and fully verified.",
        "Карта записана. Финальная проверка была пропущена.": "The drive was flashed. Final verification was skipped.",
        "Носитель клонирован и полностью проверен.": "The drive was cloned and fully verified.",
        "Носитель клонирован. Финальная проверка была пропущена.": "The drive was cloned. Final verification was skipped.",
        "Проверка пропущена. Завершаем операцию…": "Verification skipped. Finalizing…",
        "Проверка завершена. Завершаем операцию…": "Verification completed. Finalizing…",
        "Запрошена отмена. Завершаем текущий блок…": "Cancellation requested. Finishing the current block…",
        "Завершаем проверку по вашему запросу…": "Stopping verification as requested…",
        "Скачиваем образ по URL…": "Downloading image from URL…",
        "Образ полностью загружен. Подтвердите целевой накопитель.": "The image has been fully downloaded. Confirm the target drive.",
        "Ожидаем подтверждение администратора…": "Waiting for administrator approval…",
        "Проверяем карту…": "Checking the drive…",
        "Копируем носитель во временный RAW-образ…": "Copying the drive to a temporary RAW image…",
        "Сохраняем образ…": "Saving image…",
        "Проверяем образ и целевую карту…": "Checking the image and target drive…",
        "Записываем подготовленный образ на карту…": "Flashing the prepared image to the drive…",
        "Записываем образ на карту…": "Flashing image to the drive…",
        "Сверяем записанный накопитель…": "Verifying the flashed drive…",
        "Проверяем исходный и целевой носители…": "Checking source and target drives…",
        "Клонируем носитель…": "Cloning drive…",
        "Сверяем клонированный носитель…": "Verifying the cloned drive…",
        "Накопитель отключился. Ожидаем повторное подключение…": "The drive was disconnected. Waiting for it to reconnect…",
        "Освобождаем накопитель для прямого доступа…": "Releasing the drive for direct access…",
        "Накопитель временно недоступен. Пробуем снова…": "The drive is temporarily unavailable. Retrying…",
        "Распаковываем образ во временный RAW и вычисляем SHA-256…": "Extracting the image to temporary RAW and calculating SHA-256…",
        "Проверяем файловую систему ext…": "Checking the ext filesystem…",
        "Добавляем авторасширение ext при первой загрузке…": "Adding ext auto-expansion for the first boot…",
        "Уменьшаем файловую систему ext…": "Shrinking the ext filesystem…",
        "Обрабатываем свободные блоки ext…": "Processing free ext blocks…",
        "Обновляем MBR и обрезаем образ…": "Updating MBR and truncating the image…",
        "Структура ext-раздела проверена.": "The ext partition structure was verified.",
        "Сжимаем временный RAW-образ…": "Compressing the temporary RAW image…",
        "Носитель автоматически извлечён.": "The drive was automatically ejected.",
        "Автоматически извлечь носитель не удалось.": "The drive could not be ejected automatically.",
        "Для доступа к карте требуются права администратора.": "Administrator privileges are required to access the drive.",
        "Не хватает аргументов helper-процесса.": "The helper process is missing required arguments.",
        "Не указаны параметры создания образа.": "Image creation options were not provided.",
        "Не указан файл образа.": "No image file was provided.",
        "Не указан исходный носитель для клонирования.": "No source drive was provided for cloning.",
        "Неизвестный источник образа.": "Unknown image source.",
        "Неизвестная операция helper-процесса.": "Unknown helper operation.",
        "Папка для образа не существует.": "The image folder does not exist.",
        "Карта закончилась раньше ожидаемого размера.": "The drive ended before the expected size.",
        "Авторасширение ext при первой загрузке включено.": "Ext auto-expansion on first boot is enabled.",
        "Авторасширение не добавлено: в образе не найден systemd.": "Auto-expansion was not added because systemd was not found in the image.",
        "Проверяем возможность уменьшения ext-раздела…": "Checking whether the ext partition can be shrunk…",
        "Уменьшенный образ закончился раньше ожидаемого размера.": "The shrunk image ended before the expected size.",
        "Выбранный файл образа не существует.": "The selected image file does not exist.",
        "Контрольное чтение завершилось преждевременно.": "Verification reading ended prematurely.",
        "Проверка записанной карты не пройдена. Носитель нельзя считать надежной копией.": "Write verification failed. The drive cannot be considered a reliable copy.",
        "Исходный и целевой носители должны быть разными.": "The source and target drives must be different.",
        "Исходный носитель закончился раньше ожидаемого размера.": "The source drive ended before the expected size.",
        "Контрольное чтение клонированного носителя завершилось преждевременно.": "Verification of the cloned drive ended prematurely.",
        "Проверка клонированного носителя не пройдена. Его нельзя считать надёжной копией.": "Clone verification failed. The drive cannot be considered a reliable copy.",
        "устройство не найдено": "device not found",
        "Не удалось создать временный RAW-образ.": "Could not create a temporary RAW image.",
        "Образ не содержит данных.": "The image contains no data.",
        "Временный RAW-образ завершился раньше ожидаемого размера.": "The temporary RAW image ended before the expected size.",
        "ZIP и 7Z должны содержать ровно один файл образа.": "ZIP and 7Z archives must contain exactly one image file.",
        "Образ создан, но не удалось передать пользователю права на файл.": "The image was created, but file ownership could not be assigned to the user.",
        "diskutil вернул неизвестные свойства папки назначения.": "diskutil returned unknown destination folder properties.",
        "Не удалось определить физический диск папки назначения.": "Could not determine the physical disk for the destination folder.",
        "Нельзя сохранять образ на ту же карту, которую приложение будет размонтировать.": "The image cannot be saved to the same drive that will be unmounted.",
        "Некорректные аргументы helper-процесса.": "Invalid helper process arguments.",
        "Не удалось создать временный файл вывода процесса.": "Could not create a temporary process output file.",
        "Не удалось создать файл образа.": "Could not create the image file.",
        "Поток образа уже закрыт.": "The image stream is already closed.",
        "Не удалось открыть поток сжатия.": "Could not open the compression stream.",
        "Не удалось создать файлы вывода служебной команды.": "Could not create command output files.",
        "Служебный процесс завершился с ошибкой.": "The helper process failed.",
        "Введите прямую HTTP- или HTTPS-ссылку на файл образа.": "Enter a direct HTTP or HTTPS URL to an image file.",
        "Не удалось скачать образ по указанному URL.": "Could not download the image from the specified URL.",
        "Сервер вернул пустой файл образа.": "The server returned an empty image file.",
        "Не удалось определить формат загруженного файла. Нужна прямая ссылка на IMG, RAW или DD с поддерживаемым сжатием.": "Could not detect the downloaded file format. Use a direct URL to an IMG, RAW, or DD image with supported compression.",
        "Некорректный размер блока чтения.": "Invalid read block size.",
        "Структура раздела выходит за границы диска.": "The partition structure extends beyond the disk boundary.",
        "Не удалось полностью прочитать структуру файловой системы.": "Could not fully read the filesystem structure.",
        "Некорректная позиция записи.": "Invalid write offset.",
        "Запись структуры образа неожиданно остановилась.": "Writing the image structure stopped unexpectedly.",
        "Запись на накопитель неожиданно остановилась.": "Writing to the drive stopped unexpectedly.",
        "diskutil вернул неизвестный формат списка дисков.": "diskutil returned an unknown disk list format.",
        "Операция разрешена только для целого внешнего физического диска.": "This operation is allowed only for a whole external physical disk.",
        "Встроенные инструменты ext2/3/4 отсутствуют или повреждены. Переустановите Simple Imager.": "Bundled ext2/3/4 tools are missing or damaged. Reinstall Simple Imager.",
        "Накопитель слишком мал для таблицы разделов MBR.": "The drive is too small for an MBR partition table.",
        "Таблица разделов MBR не найдена.": "No MBR partition table was found.",
        "В MBR не найдено ни одного раздела.": "No partitions were found in the MBR.",
        "GPT пока не поддерживается.": "GPT is not supported yet.",
        "Расширенные и логические разделы пока не поддерживаются.": "Extended and logical partitions are not supported yet.",
        "Один из разделов выходит за границы накопителя.": "A partition extends beyond the drive boundary.",
        "Последний основной раздел должен иметь Linux-тип 0x83.": "The last primary partition must have Linux type 0x83.",
        "Раздел слишком мал для ext2/3/4.": "The partition is too small for ext2/3/4.",
        "В последнем разделе не найдена файловая система ext2/3/4.": "No ext2/3/4 filesystem was found in the last partition.",
        "macOS не создала устройство для уменьшаемого ext-раздела.": "macOS did not create a device for the ext partition being shrunk.",
        "resize2fs вернул некорректный минимальный размер файловой системы.": "resize2fs returned an invalid minimum filesystem size.",
        "Не удалось вычислить итоговый размер файловой системы.": "Could not calculate the final filesystem size.",
        "Итоговый раздел не помещается в таблицу MBR.": "The resulting partition does not fit in the MBR.",
        "Обнуляем свободные блоки ext…": "Zeroing free ext blocks…",
        "Обновляем таблицу разделов и размер образа…": "Updating the partition table and image size…",
        "Не удалось проверить файлы авторасширения в ext-образе.": "Could not verify auto-expansion files in the ext image.",
        "Переполнение при вычислении свободного места ext-раздела.": "Overflow while calculating free ext space.",
        "debugfs не сообщил блоки временного файла очистки.": "debugfs did not report blocks for the temporary cleanup file.",
        "Не удалось создать временный файл очистки ext.": "Could not create the temporary ext cleanup file.",
        "Не удалось разобрать минимальный размер из ответа resize2fs.": "Could not parse the minimum size reported by resize2fs.",
        "Не удалось разобрать геометрию файловой системы из ответа tune2fs.": "Could not parse filesystem geometry reported by tune2fs.",
        "Переполнение при вычислении размера образа.": "Overflow while calculating the image size.",
        "Таблица MBR временного образа неожиданно изменилась.": "The temporary image MBR changed unexpectedly."
    ]

    private static let fragments: [(String, String)] = [
        ("После переподключения под именем ", "After reconnection, "),
        (" обнаружен другой накопитель. Обновите список и выберите карту заново.", " now refers to a different drive. Refresh the list and select the drive again."),
        ("Целевой накопитель меньше образа: нужно минимум ", "The target drive is smaller than the image. Required: "),
        ("Целевой накопитель меньше исходного: нужно минимум ", "The target drive is smaller than the source. Required: "),
        ("Распакованный образ больше целевого накопителя размером ", "The extracted image is larger than the target drive of "),
        ("Не удалось открыть накопитель для ", "Could not open the drive for "),
        (" за ", " within "),
        (" секунд. ", " seconds. "),
        ("Проверьте карту, кардридер и кабель.", "Check the card, reader, and cable."),
        ("Последняя ошибка: ", "Last error: "),
        ("Недостаточно места для промежуточного RAW-образа. Нужно не менее ", "Not enough space for the temporary RAW image. Required: "),
        (", доступно ", ", available: "),
        ("Образ уменьшен с ", "Image shrunk from "),
        (" до ", " to "),
        (" и сохранён как ", " and saved as "),
        ("Образ сохранён в формате ", "Image saved as "),
        ("Для формата ", "The "),
        (" требуется выполнить: ", " format requires: "),
        ("На этом Mac отсутствует инструмент для формата ", "This Mac is missing the tool required for "),
        ("Не удалось запустить ", "Could not launch "),
        ("Команда завершилась с кодом ", "The command exited with status "),
        ("Не удалось скачать образ.", "Could not download the image."),
        ("Недопустимый идентификатор диска: ", "Invalid disk identifier: "),
        ("Не удалось прочитать свойства ", "Could not read properties for "),
        ("Не удалось найти ", "Could not find "),
        ("Не удалось получить идентификатор IORegistry для ", "Could not obtain the IORegistry ID for "),
        ("Не удалось получить путь IORegistry для ", "Could not obtain the IORegistry path for "),
        ("Не найден встроенный инструмент ", "Bundled tool not found: "),
        ("Не удалось подключить временный образ", "Could not attach the temporary image"),
        ("Не удалось отключить временный образ", "Could not detach the temporary image"),
        ("hdiutil подключил образ, но не сообщил имя устройства.", "hdiutil attached the image but did not report a device name."),
        ("В Linux-образе отсутствует каталог ", "The Linux image is missing directory "),
        ("Не удалось создать каталог ", "Could not create directory "),
        (" в ext-образе.", " in the ext image."),
        ("debugfs не создал ", "debugfs did not create "),
        ("debugfs не смог проверить ", "debugfs could not verify "),
        ("debugfs не смог прочитать ", "debugfs could not read "),
        ("debugfs не выполнил команду для ext-образа", "debugfs failed to run a command on the ext image"),
        ("Не удалось заполнить свободные блоки ext", "Could not fill free ext blocks"),
        ("debugfs не смог перечислить свободные блоки ext", "debugfs could not list free ext blocks"),
        ("Не удалось исправить временную копию ext-раздела", "Could not repair the temporary ext partition copy"),
        ("Проверка ext-раздела не пройдена", "Ext partition verification failed"),
        ("resize2fs не смог уменьшить файловую систему", "resize2fs could not shrink the filesystem"),
        ("resize2fs не смог определить минимальный размер", "resize2fs could not determine the minimum size"),
        ("tune2fs не смог прочитать параметры ext-раздела", "tune2fs could not read ext partition parameters"),
        ("Не удалось обрезать временный образ: ", "Could not truncate the temporary image: "),
        ("Уменьшение доступно для последнего основного раздела ext2/3/4 в MBR.", "Shrinking is available for the last primary ext2/3/4 partition in an MBR image."),
        ("Отключите «Уменьшить ext» или создайте обычный образ.", "Disable Shrink image or create a regular image."),
        ("Кодек ", "Codec "),
        (" не смог создать образ.", " could not create the image."),
        (" не смог распаковать образ.", " could not extract the image."),
        ("Ошибка ", "Error while "),
        (" накопителя: ", " the drive: "),
        ("Накопитель ", "Drive "),
        (" исчез из системы.", " disappeared from the system."),
        ("Переподключите карту или кардридер и повторите операцию.", "Reconnect the card or reader and try again."),
        ("macOS заблокировала прямой доступ к накопителю.", "macOS blocked direct access to the drive."),
        ("Включите «Полный доступ к диску» для приложения «Simple Imager» в разделе «Конфиденциальность и безопасность», затем полностью перезапустите приложение.", "Enable Full Disk Access for Simple Imager in Privacy & Security, then restart the application."),
        ("Не удалось прочитать структуру архива.", "Could not read the archive structure."),
        ("Не удалось безопасно определить накопитель папки назначения.", "Could not safely identify the drive containing the destination folder."),
        ("Выберите другую папку и повторите попытку.", "Select another folder and try again."),
        ("Не найдены: ", "Missing: "),
        ("Проверено файлов: ", "Verified files: "),
        (", утилит: ", ", tools: "),
        ("Проверка SHA-256 не пройдена: ", "SHA-256 verification failed: "),
        ("набор утилит неполон", "the tool set is incomplete"),
        ("Переустановите приложение.", "Reinstall the application."),
        ("Homebrew для работы не требуется.", "Homebrew is not required."),
        ("код ", "code ")
    ]
}
